name: telestream
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  shared_preferences: ^2.3.2
  animated_text_kit: ^4.2.2
  gap: ^3.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  flutter_gen: ^5.8.0
  build_runner: ^2.4.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
